apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: product
build:
  artifacts:
  - image: edjaz/product/service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-debug/product.yml
