apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: product
build:
  artifacts:
  - image: edjaz/product/service
    jib:
      project: microservices:product:service
      type: gradle
deploy:
  kubectl:
    manifests:
    - k8s-debug/product.yml
