apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: auth-server
build:
  artifacts:
  - image: edjaz/auth-server
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-debug/auth-server.yml
