apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: auth-server
build:
  artifacts:
  - image: edjaz/auth-server
    jib:
      project: spring-cloud:authorization-server
      type: gradle
deploy:
  kubectl:
    manifests:
    - k8s-debug/auth-server.yml
