apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
        version: v2
    spec:
      containers:
        - name: pro
          image: edjaz/product/service:v2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,prod,kubernetes"
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "400Mi"
