spring.config.import: configserver:${SPRING_CLOUD_CONFIG_URI}

spring:
  application.name: gateway
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
    gateway:
      discovery:
        locator:
          enabled: true

spring.cloud.kubernetes.enabled: false


