server.port: 7001

server.error.include-message: always
server.error.include-binding-errors: always

spring.data.mongodb:
  auto-index-creation: true
  host: localhost
  port: 27017
  database: product-db
  authentication-database: admin
  username: mongodb-user-dev
  password: '{cipher}5a9ee7cf7c97d9b210a3c277ba85c8802e9689442612354e8eb4e860ea7f7efd'

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.sink-in-0:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

logging:
  level:
    root: INFO
    fr.edjaz: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.data.mongodb.host: mongodb

---
spring.config.activate.on-profile: streaming_partitioned
spring.cloud.stream.bindings.input.consumer:
  partitioned: true
  instanceCount: 2

---
spring.config.activate.on-profile: streaming_instance_0
spring.cloud.stream.bindings.input.consumer.instanceIndex: 0

---
spring.config.activate.on-profile: streaming_instance_1
spring.cloud.stream.bindings.input.consumer.instanceIndex: 1


