apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-server-vs
spec:
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /oauth
      route:
        - destination:
            host: auth-server
            port:
              number: 9999
            subset: old
          weight: 100
        - destination:
            host: auth-server
            port:
              number: 9999
            subset: new
          weight: 0
