apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: review
build:
  artifacts:
  - image: edjaz/review/service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-debug/review.yml
