apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: review
build:
  artifacts:
  - image: edjaz/review/service
    jib:
      project: microservices:review:service
      type: gradle
deploy:
  kubectl:
    manifests:
    - k8s-debug/review.yml
