spring:
  application.name: eureka-server
spring.config.import: configserver:${SPRING_CLOUD_CONFIG_URI}
spring.cloud.config:
  failFast: true
  retry:
    initialInterval: 3000
    multiplier: 1.3
    maxInterval: 10000
    maxAttempts: 20
