apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: edjaz/auth-server
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,kubernetes"
            - name: SPRING_CONFIG_LOCATION
              value: file:/config-repo/application.yml,file:/config-repo/auth-server.yml
          envFrom:
            - secretRef:
                name: rabbitmq-credentials
          ports:
            - containerPort: 9999
          volumeMounts:
            - name: config-repo-volume
              mountPath: /config-repo
      volumes:
        - name: config-repo-volume
          configMap:
            name: config-repo-auth-server
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  selector:
    app: auth-server
  ports:
    - port: 9999
      targetPort: 9999

