spring:
  application.name: auth-server

spring.cloud.config:
  failFast: true
  retry:
    initialInterval: 3000
    multiplier: 1.3
    maxInterval: 10000
    maxAttempts: 20

---
spring.config.activate.on-profile: config
spring.config.import: configserver:${SPRING_CLOUD_CONFIG_URI}

---
spring.config.activate.on-profile: kubernetes
spring.cloud.kubernetes.enabled: true
eureka.client.enabled: false
spring.cloud.config.enabled: false
