apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: product-composite
build:
  artifacts:
  - image: edjaz/product-composite/service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-debug/product-composite.yml
