apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: recommendation
build:
  artifacts:
  - image: edjaz/recommendation/service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-debug/recommendation.yml
