apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: recommendation
build:
  artifacts:
  - image: edjaz/recommendation/service
    jib:
      project: microservices:recommendation:service
      type: gradle
deploy:
  kubectl:
    manifests:
    - k8s-debug/recommendation.yml
