apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: edjaz/gateway
        imagePullPolicy: Never
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "docker,kubernetes"
          - name: SPRING_CONFIG_LOCATION
            value: file:/config-repo/application.yml,file:/config-repo/gateway.yml
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 500Mi
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health/liveness
            port: 4004
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 20
          successThreshold: 1
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health/readiness
            port: 4004
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
          - name: config-repo-volume
            mountPath: /config-repo
      volumes:
        - name: config-repo-volume
          configMap:
            name: config-repo-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 4004
      name: http-mgm
      targetPort: 4004
