apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge-ngrok
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer-prod"
spec:
  tls:
    - hosts:
        - d9c1a0fb.ngrok.io
      secretName: tls-ngrok-letsencrypt-certificate
  rules:
    - host: d9c1a0fb.ngrok.io
      http:
        paths:
          - path: /oauth
            backend:
              service:
                name: auth-server
                port:
                  number: 9999
          - path: /product-composite
            backend:
              service:
                name: product-composite
                port:
                  number: 8080
          - path: /actuator/health
            backend:
              service:
                name: product-composite
                port:
                  number: 8080
